name: Update Windows 11 ISO Link

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:     # Allow manual triggers

jobs:
  update-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager
          
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: Get Windows 11 ISO link
        run: |
          python scripts/get_win11_iso.py
        
      - name: Update link file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add win11_iso_link.txt
          git commit -m "Update Windows 11 ISO link" || echo "No changes to commit"
          git push
